import React, {useEffect} from "react";
import HeroHeader from "../components/HeroHeader";
import Footer from "../components/Footer";
import CreditMain from "../components/CreditMain";
import CreditHeader from "../components/CreditHeader";
import Head from "next/head";

const Credit = () => {


    
    useEffect(()=> {
        window.onload = () => {
            console.log("page loaded")
        }
    })

	return (
		<div>
			<Head>
				<title>Credit</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main>
				<HeroHeader />

				<div className='px-[20px] lg:px-[72px]  w-full h-full'>
					<CreditHeader />
					<CreditMain />
					<Footer />
				</div>
			</main>
		</div>
	);
};

export default Credit;
