import Head from "next/head";
import Image from "next/image";
import HeroHeader from "../components/HeroHeader";
import HeroMain from "../components/HeroMain";
import HeroFooter from "../components/HeroFooter";
import { useState, useEffect } from "react";
import Footer from "../components/Footer";
import HeroSecond from "../components/HeroSecond";
import HeroFoot from "../components/HeroFoot";
import { Modal } from "@mui/material";
import MusicModal from "../components/MusicModal";

export default function Home() {
    useEffect(() => {

    }, []);

    const [open, setOpen] = useState(true)


    const [play, setPlay] = useState(false);


    const Play = () => {
        setPlay(!play);
        console.log(play);
        localStorage.setItem("play", play);
    };

    return (
        <div className=''>
            <Head>
                <title>CSC 2021-22</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <HeroHeader />

            
               
                    <>
                        <main className='px-[20px] lg:px-[72px]  w-full h-full relative flex flex-col  '>
                            <HeroMain />
                            <HeroFooter />
                        </main>
                        <HeroSecond />
                        <HeroFoot />
                        <div className='px-[20px] lg:px-[72px] w-full h-full '>
                            <Footer />
                        </div>
                    </>
            


        </div>
    );
}
