import React from "react";
import GalleryHeader from "../components/GalleryHeader";
import GalleryMain from "../components/GalleryMain";
import YearbookMain from "../components/YearbookMain";
import Head from "next/head";
import Footer from "../components/Footer";

const Gallery = () => {

    
    // window.onload = () => {
    //     console.log("page loaded")
    // }


	return (
       <div>
         <Head>
				<title>Yearbook</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
		<main >
			<div className='scroll-hidden  h-full w-full'>
				<div className='h-full w-full'>
					<YearbookMain />
				</div>
			</div>			
		</main>
        <div className='px-[20px] lg:px-[72px] w-full h-full mt-[56px]'>
				<Footer />
			</div>
       </div>
	);
};

export default Gallery;
